### ISSUE TITLE
Add conda installation to docs

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#106]
Update docs with instructions to install CPU version of galario with conda from conda-forge channel

**Comment by fredRos** [comment]
From #93 
> But I think it's easier to just state: with conda, there is no cuda support. One has to build galario manually to run on the gpu.

**Comment by mtazzari** [comment]
Fixed by 1ae7abec5ac9f1fa3da9968666ad12a519a8b354

The commit message did not parse the "and" correctly.

**Comment by mtazzari** [comment]
Fixed by 1ae7abec5ac9f1fa3da9968666ad12a519a8b354

The commit message did not parse the "and" correctly.
