### ISSUE TITLE
Call all functions in C++ tests

### ISSUE THREAD

**Issue by fredRos** [mtazzari/galario#113]
Issue #109 could have been detected if we had called all galario API functions from a compiled example. We have such an example but so for it serves only as a test that linking works. Calling all functions but not producing segfaults requires valid input data, which isn't easy to do given the various physics constraints. In the worst case, we'd have to duplicate what is in the python tests but an easier approach would be very much welcome.

**Comment by mtazzari** [comment]
@fredRos isn't this well solved with the `galario_test.cpp`?

**Comment by fredRos** [comment]
Closing as won't do
