### ISSUE TITLE
Improve docs by adding index in the left navbar

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#116]
It would be very useful to have the full index in the left navbar. 
At the moment there are only the main level pages, but it is not very handy the fact that Contents is at the bottom of the home page.
Having the Contents in the left navbar would make navigation easier.

**Comment by fredRos** [comment]
I support this. It confused me, too

**Comment by mtazzari** [comment]
This is useful:
https://stackoverflow.com/questions/18969093/how-to-include-the-toctree-in-the-sidebar-of-each-page

But this is the solution, as pointed out on the SO second answer:
https://pypi.org/project/sphinxcontrib-fulltoc/
