### ISSUE TITLE
libcommon.reduce_chi2() modifies input

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#117]
In the libcommon.reduce_chi2() funciton, with signature:
```
reduce_chi2(dreal[::1] vis_obs_re, dreal[::1] vis_obs_im, dreal[::1] vis_obs_w, dcomplex[::1] vis):
```
the model visibilities passed in input as `vis` are modified inplace by the C code.
This is disruptive and should be fixed. Solution: create a copy at Python level before calling the C function reduce_chi2() as we have done for `libcommon.apply_phase_vis`.

**Comment by fredRos** [comment]
is this on a current version? I thought this was fixed in https://github.com/fredRos/galario/commit/19ffc145f67922accf6d8235c8d216bd8087850c, see also #77

**Comment by mtazzari** [comment]
Yes, the issues is on the current version, latest master commit ccda3f773513d2fff25dae1a419bff42e166c386

**Comment by fredRos** [comment]
I agree it shouldn't overwrite anymore, that would be a bug. Did this occur on CPU or GPU?

**Comment by mtazzari** [comment]
On CPU for sure
