### ISSUE TITLE
pip installation

### ISSUE THREAD

**Issue by fredRos** [mtazzari/galario#122]
Create a lightweight pkg on pypi that just git clones this repo and inside `setup.py` calls `cmake`. The advantage over the conda pkg would be to use cuda, if available. Luckily on the mac there are no more cuda cards so people don't have to make a hard choice

**Comment by mtazzari** [comment]
This could be useful to detect in which directory the package should be stored:
https://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory

e.g. with
```
python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
```

**Comment by fredRos** [comment]
Looking at the number of corner cases we describe in our installation instructions, a pip installation is likely to fail for many people. They would then complain and we could only advise them to go back to manual compilation. So I think let's not fool people and cause ourselves unnecessary work.

Manual compilation or conda
