### ISSUE TITLE
Automated benchmark speed test

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#128]
For the long term development it would be useful to have an automated way of running the speed tests. This would prevent to inadvertently slow down the code.
Specifications:
 - It could be, e.g. part of unit tests disabled by default and executed only if specifically selected.
 - It should make a number comparison so that it can be used with the `git bisect` command to find when slow down was introduced.
 - It could be necessary, though, to update the reference values if the test will be run on a different machine. In principle we could support different machines.
 - it would not be run by travis but on a local machine (too much work to setup a test machine locally)

To evaluate: what is an acceptable tolerance?

**Comment by fredRos** [comment]
won't do
