### ISSUE TITLE
Credit to GPU workshop

### ISSUE THREAD

**Issue by fredRos** [mtazzari/galario#162]
I don't see a credit to the workshop where it all began in the docs. I think we put this into the acknowledgment section in the paper but we should also have this in the docs  because we also acknowledge code contributions by name

**Comment by mtazzari** [comment]
I agree, thanks Fred for spotting this.
We can put it in the docs index.html, at the bottom of the “Contributors" section.
I suggest we put an abridged version of statement we used in the paper.
