### ISSUE TITLE
Add link to paper citations

### ISSUE THREAD

**Issue by fredRos** [mtazzari/galario#163]
In the docs, there is a list of papers that used galario before or around the time the paper was published. But ADS can just keep track of that with this query so we don't have to update it manually

https://ui.adsabs.harvard.edu/#search/q=citations(bibcode%3A2018MNRAS.476.4527T)%20OR%20doi%3A10.1051%2F0004-6361%2F201527516%20OR%20doi%3A10.1051%2F0004-6361%2F201527423%20OR%2010.1051%2F0004-6361%2F201730890%20OR%2010.1051%2F0004-6361%2F201628623&sort=date%20desc%2C%20bibcode%20desc&p_=0

You can see that I added the old DOIs by hand, so you can still add papers, if needed

**Comment by mtazzari** [comment]
Absolutely!
In the publications page we simply replace the content with this link.
Perhaps it'll be worth adding it to the README as well.

**Comment by fredRos** [comment]
Your call where to put it
