### ISSUE TITLE
Initial guess for the parameters

### ISSUE THREAD

**Issue by bjnorfolk** [mtazzari/galario#170]
Hi,

I've edited my previous post, I'm wondering how to choose f0 the normalising parameter and sigma for the Gaussian profile? i.e. what's the best method for estimating these values in the initial guess?

Thanks,
Brodie

**Comment by mtazzari** [comment]
Hi Brodie,

in the [quickstart example](https://mtazzari.github.io/galario/quickstart.html) you see that the profile normalisation is typically best sampled in the log space (it can span multiple orders of magnitude), while sigma is better in linear scale.
The MCMC chain will explore quite rapidly the parameter space, so the initial guess is not so important as long as you choose starting values from withing the central part of the parameter space. E.g. if sigma can range between 0. and 1., I'd pick a value between 0.2 and 0.8.
