### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#183]
From Nov 2020 Travis CI essentially dropped support for open source projects by reducing the free credits, and by requiring one to apply to request credits.

See an excellent summary [here](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works)

So, let's move to GitHub Actions, which is completely Free for open source (i.e., public on GitHub) projects! Jaaaaay!

**Comment by fredRos** [comment]
yeah, similar story over here https://github.com/pypmc/pypmc/issues/74

**Comment by mtazzari** [comment]
yeah I see! I've already done this in my uvplot package yesterday: https://github.com/mtazzari/uvplot/pull/50
The tricky bit, if you want to test/automate packaging and upload to PyPI is that even TestPyPI forbids uploading the same package with same version. 
So in order to test packaging and uploading to TestPyPI I came up with a workaround that changes the package version on-the-fly only in the test workflow on all branches but master. This allows testing for packaging each commit in every PR.
