### ISSUE TITLE
Transfer observations

### ISSUE THREAD

**Issue by fredRos** [mtazzari/galario#27]
The primary intended usage of galario is to call it inside a fit where the observed data never change. We could save some time by copying this over to the GPU only once, then reuse it. Before implementing that, I should profile and estimate whether it helps at all. Perhaps the transfer of the model image takes much longer and that has to be transferred every time if the image is generated on the CPU

**Comment by mtazzari** [comment]
We will not support this because we don't want to handle runtime memory management on the GPU.
