### ISSUE TITLE
Better tests

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#46]
We should re-organize the tests in `test_galario.py`:

- [ ] **reduce repetition**, e.g. create a `setup()` function that creates reference image, sampling points etc. that is called once at the beginning;
- [ ] **choose uniform parametrization**: many tests have similar but not identical parametrizations. Try to make this uniform, in many cases it should be possible
    - [ ] parametrize such that all the tests are repeated for different matrix sizes, nsamples, etc.

- [ ] **add informative printouts**: when a test fail, the default output of `numpy.testing.assertequal` is not very useful. Try to add essential yet informative printout to help debugging.

Some of these proposals might require using objects e.g. to store the static output of `setup()`.

**Comment by fredRos** [comment]
I think we have done most or all of it, so let's close this old dinosaur
