### ISSUE TITLE
GPU optimization/profiling/timing

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#53]
I have made some profiling on my desktop calx174 (GTX 1060) with :
```
nvprof --export-profile filename.prof python python/speed_benchmark_dp.py --gpu
``` 
IMPORTANT: in `speed_benchmark_dp.py` I commented out the first `acc_lib.sample()`, so that this profiling contains only `acc_lib.chi2()`.
 
A few notes, regarding the screenshot. Here I considered matrix size 4096, nsamples 1e6, 64 nthreads

![screen shot 2017-07-13 at 12 13 35](https://user-images.githubusercontent.com/6020226/28164175-0d3f3422-67c6-11e7-9889-2fe8f59cccb6.png)

1. below the graphical timeline, you can see interesting numbers for each kernel.
2. one very **big** and **good** news: with nthreads=64, `real_to_complex` and `shift_d` disappear! We are hugely dominated by the `MemcpyHtoD` and by the `cuFFT_C2C` (to which the several `dpRadix` come from). I double checked this: leaving everything the same, and just setting `nthreads=32`, `real_to_complex` and `shift_d` come up again as ~50%. I think we are in good position, since we want to go large with `nthreads` and there is no reason to use 32.
3. The `Memcpy` commands are synchronous: with async Memcpy (and/or streams, not sure if they imply each other) that we could save up to 1.3ms*5 = 6.5ms hiding the  `Memcpy` of the 1d arrays (size ~8MB) under the 2d `Memcpy` of the image.
4. If I sum up the "Duration" column of all the kernels, I get ~65ms, which is similar to the 60ms measured from timings (see my comment in #52). The processes listed there do not contain the big `cudaFree` slots.
5. and the `cudaFree` slots? I am getting convinced that the `cudaFree` that we launch are **not** causing the big `cudaFree` blocks of ~300ms in the timeline. To test this, I commented out all the `cudaFree` in `galario.cpp` and I see no difference in the timeline nor in the timings. I thus believe that the 0.6ms that the manual timing gives is accurate and when we call `chi2()` without `nvprof` we don't get these overheads.
6. `cublasCreateHandle`: I think it causes the MemcpyH2D at the very end, it is called in `reduce_chi2_d` just before `diff_weighted_d`. See a snapshot here with a zoom on the very final part (time >~1.6s in previous snapshot):
 
![screen shot 2017-07-13 at 12 55 38](https://user-images.githubusercontent.com/6020226/28165193-b0324198-67ca-11e7-91bf-103f6ff4b962.png)

Since this MemcpyH2D is synchronous, it could introduce delay due to latency since it causes a Malloc after interpolated_d and before diff_weighted_d.  Perhaps, we could move this create handle at the beginning of `sample_d`, after the initial Memcpys and pass the handle to `reduce_chi2_d`, then destroy the handle in `sample_d`. Here the docs: 
 [cublasCreate](http://docs.nvidia.com/cuda/cublas/index.html#cublascreate)
> Because cublasCreate allocates some internal resources and the release of those resources by calling cublasDestroy will implicitly call cublasDeviceSynchronize, **it is recommended to minimize the number of cublasCreate/cublasDestroy occurences**. For multi-threaded applications that use the same device from different threads, the recommended programming model is to create one CUBLAS handle per thread and **use that CUBLAS handle for the entire life of the thread**.

These are results. Next comment: proposals where to go from here, prioritization of the optimizations.

**Comment by fredRos** [comment]
`cuda_malloc` and `cuda_free` simply take a lot longer on the gpu than on the cpu. Accurate timings are now part of the code, and plots in our paper show the break down into suboperations.
