### ISSUE TITLE
Use streams to avoid blocking GPU while copying

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#60]
An important point is raised in this blog post:

https://devblogs.nvidia.com/parallelforall/how-overlap-data-transfers-cuda-fortran/

If we use the default stream, we and nobody else can overlap copy and execution. As library authors, we should not use the default stream!

**Comment by mtazzari** [comment]
Try compiling with the `--default-stream per-thread` option!
here docs:
https://devblogs.nvidia.com/parallelforall/gpu-pro-tip-cuda-7-streams-simplify-concurrency/

**Comment by fredRos** [comment]
Ôh man, such an easy solution. I will create a PR for @mtazzari to test on his GPU
