### ISSUE TITLE
Simplify function interface

### ISSUE THREAD

**Issue by fredRos** [mtazzari/galario#68]
`chi2` takes many arguments. Some structs could simplify that. For example

```cpp
struct Observations {
 const dreal* fobs_re, const dreal* fobs_im, const dreal* weights
};
```

**Comment by fredRos** [comment]
We won't do this now but in the future we may have classes that hold data

**Comment by mtazzari** [comment]
This will be solved when I will implement the separate package that uses casacore to extract visibilities from MS files

**Comment by fredRos** [comment]
so we can close this issue now I guess
