### ISSUE TITLE
Proper licensing

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#96]
At the moment the LICENSE is missing the last bit, point 6.
Also, GNU instructions suggest to add a note at the top of each source file.

Follow instructions here:
https://choosealicense.com/licenses/lgpl-3.0/

**Comment by mtazzari** [comment]
Instructions on **How to Apply These Terms to Your New Programs**

>  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.
 > To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    {one line to give the program's name and a brief idea of what it does.}
    Copyright (C) {year}  {name of author}

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

Also add information on how to contact you by electronic and paper mail.

**Comment by fredRos** [comment]
Ok with me. We don't have many source files anways. We won't update the docs with this notice. You are welcome to get your hands dirty!

**Comment by mtazzari** [comment]
This would be the text to add on top of each file:

```
"""
galario - a GPU Accelerated Library for Analysing Radio Interferometer Observations
Copyright (C) 2017  Marco Tazzari, Frederik Beaujean, Leonardo Testi

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
```

However, reading on the web several sources I think it is not necessary.

**Comment by mtazzari** [comment]
I therefore close the issue
